### ISSUE TITLE
Problem to load openslide-jni.dll

### ISSUE THREAD

**Issue by ADietrich** [openslide/openslide-java#21]
I have started to implement a project to load medical data by using OpenSlide and I have decided to use the Java interface. The current version of OpenSlide Windows binaries (openslide-win64-20150527) I have unzipped and set the PATH variable to the bin sub folder.
The OpenSlide Java interface in latest version 0.12.1 I have downloaded too and try to start your demo app and also implement own code with creating an OpenSlide object. But in both cases I got an "UnsatisfiedLinkError" with the message, that in the library openslide-jni.dll the specified procedure could not be found.

Is there a problem with the current Windows binaries? I have tried also the older version from 2015-04-20, because the last Java interface is from the same date, but it doesn't solve the problem.

The "openslide.jar" in bin folder I can start. It works wonderful and I want to have this nice features in my program too.

Summery:
- Windows Binaries 64 bit from 2015-05-27 or 2015-04-20 (with both tested)
- Java interface 0.12.1
- OS: Windows 7 Pro with SP1
- Java 1.8.0_25

**Comment by bgilbert** [comment]
So, OpenSlide Java works fine if you use the copy included with the Windows binaries, but it doesn't work when you build it separately?

**Comment by bgilbert** [comment]
So, OpenSlide Java works fine if you use the copy included with the Windows binaries, but it doesn't work when you build it separately?  How are you building it?  Could you double-check that `PATH` includes the bin directory?

**Comment by ADietrich** [comment]
Yes. The included openslide.jar works and I think this Java app uses the library "openslide-jni.dll" too. But when I run your Java demo project or an own Java project this library can't be load.

Tha PATH variable in Windows I have set to the bin directoy of unzipped folder "openslide-win64-20150527". The build prozess finds the dll file, otherside another error is shown in the log (I have tested it).

Anything I do wrong, because I don't think, that the library is broken (because your jar works with it).

**Comment by ADietrich** [comment]
Currently I try to implement my code in a virtual machine with Linux. But my Linux experiences are not so good and I prefer to work with Windows. Maybe you can help me.

**Comment by ADietrich** [comment]
Update: A colleague has tested the same on his Windows System and there it works!!! He has Windows 7 64bit too, has unzipped the Windows binaries and set the bin folder into his PATH variable. He uses the same origin demo code inside your Java interface package and he uses Java 8. But on his system your demo was built and start (shows open file dialog).

Are there any additional dependencies, which are missing on my system, but which openslide needs to build? I have started to compair the colleague system with mine.

**Comment by ADietrich** [comment]
The problem is solved!!! 

We have found, that in my system there are more than one of the depended library "zlib1.dll" and the PATH variable include a place to another "zlib1.dll" before my added path to the directory "openslide-win64-20150527". A simple moving from this path before the other path solves the problem.

And the PATH variable of the Windows system of my colleague doesn't have the path to the other version of the "zlib1.dll".

Nevertheless thanks for your support and your quickly answer.

Greetings
Andreas Dietrich
