### ISSUE TITLE
Not able to run Demo file

### ISSUE THREAD

**Issue by sainarendra74** [openslide/openslide-java#42]
Installed openslide and followed **Building on Linux or Mac OS X** instructions. It generated libopenslide-jni.so file and everything seems as expected. But I'm not able to run the demo.java file.

It's giving the following **error**:

/usr/lib/jvm/java-11-openjdk-amd64/bin/java: symbol lookup error: /usr/local/lib/openslide-java/libopenslide-jni.so: undefined symbol: openslide_get_version

**Comment by bgilbert** [comment]
Could you post the output of `ldd /usr/local/lib/openslide-java/libopenslide-jni.so`?

**Comment by sainarendra74** [comment]
Thanks for the reply.
I created .so file from openslide-jni.c using the following command

gcc openslide-jni.c -shared -o libopenslide-jni.so -lopenslide -I/usr/local/include/openslide -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux/ -I/usr/lib/jvm/java-11-openjdk-amd64/include/

And replaced with the previously generated .so file. It's working.

**Comment by bgilbert** [comment]
There's not enough info here to debug this, and it sounds like you've found a workaround, so I'll go ahead and close.  If you're able to provide the requested information, please feel free to reopen.
