### ISSUE TITLE
 OpenSlideCache and DeepZoomGenerator api

### ISSUE THREAD

**Issue by chengdonglin** [openslide/openslide-java#54]
I find python api has the  OpenSlideCache and DeepZoomGenerator  interface. I build project by ant, I not find them, is not support for java?

**Comment by bgilbert** [comment]
Cache configuration hasn't been implemented yet; see #36.

Deep Zoom generation is a feature of OpenSlide Python, not of OpenSlide itself.  There are currently no plans to implement it for OpenSlide Java.
