### ISSUE TITLE
dependency openslide found: NO (tried pkgconfig)

### ISSUE THREAD

**Issue by h616016784** [openslide/openslide-java#55]
centos7，meson build
提示：
WARNING: The version of Make /usr/bin/cmake is 2.8.12.2 but version >=3.4 is required
Run-time dependency openslide found: NO (tried pkgconfig)
meson. build: 75:12: ERROR: Dependency "openslide" not found, tried pkgconfig

已经成功安装了openslide，why？

**Comment by bgilbert** [comment]
OpenSlide Java requires [OpenSlide](https://github.com/openslide/openslide).  Is OpenSlide installed?

**Comment by h616016784** [comment]
i dont know is right  installed？
i run ：
   First, install [EPEL](https://fedoraproject.org/wiki/EPEL).
   yum install openslide
here is result：
![企业微信截图_16915479078010](https://github.com/openslide/openslide-java/assets/9603152/109b01c7-12a8-4a81-a32c-3cc66c04d1f7)
![企业微信截图_16915488023570](https://github.com/openslide/openslide-java/assets/9603152/d5759710-52a9-437d-afb9-737b7e2bacd1)

and i installed Meson and pkg-config
then i enter this project and  run ：meson setup builddir
here is the result ：
<img width="1562" alt="企业微信20230809-162825@2x" src="https://github.com/openslide/openslide-java/assets/9603152/0c70f6e9-8b6c-4baa-b8c2-90c801c31027">

i dont know why not find openslide？
i think that i do not installed openslide in right way？because i installed it in my mac computer，here is the result：
<img width="1394" alt="企业微信截图_20959c18-4f6b-4bf8-b21e-44f13bf54c25" src="https://github.com/openslide/openslide-java/assets/9603152/098c5be2-5d42-48f5-a107-d08f37c3fd3b">

or should i config the path？but i run “meson setup builddir ” in my mac computer，i dont config the path，it works。
so i dont know Where did I go wrong，Please help me，thanks！

**Comment by bgilbert** [comment]
You should also `yum install openslide-devel`.  To build OpenSlide Java, you need the files from that package.

**Comment by h616016784** [comment]
it works！
Thank you so much！
I suggest that readme add yum install openslide-devel in centos，If I'm a junior developer，It was hard for me to know that this step was needed。

**Comment by bgilbert** [comment]
#71 removes the requirement to install `openslide-devel` before building OpenSlide Java.  Thanks for reporting this!
